version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quriobot_shopify
      - MYSQL_ROOT_PASSWORD=CE0^wXfE9P
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: quriobot-shopify-app
    build:
      context: ./
      target: production
    image: quriobot-shopify-app
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: CE0^wXfE9P
      DB_NAME: quriobot_shopify
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local